version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu

hooks:
 BeforeInstall:
  - location: scripts/cleanup_server.sh
    timeout: 600
    runas: root
 AfterInstall:
  - location: scripts/postinstall.sh
    timeout: 6000
    runas: ubuntu
 ApplicationStart:
  - location: scripts/startapp.sh
    timeout: 6000
    runas: ubuntu