# Generated by Django 3.0.2 on 2020-01-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='uuid_id',
            new_name='id',
        ),
    ]
