# Generated by Django 3.0.2 on 2020-02-10 07:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20200127_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillFile',
            fields=[
                ('file_name', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='account created')),
            ],
        ),
        migrations.AlterField(
            model_name='bills',
            name='paymentStatus',
            field=models.CharField(choices=[('paid', 'paid'), ('due', 'due'), ('past_due', 'past_due'), ('no_payment_required', 'no_payment_required')], max_length=20),
        ),
        migrations.AddField(
            model_name='bills',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.BillFile'),
        ),
    ]
