# Generated by Django 3.0.2 on 2020-02-11 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20200211_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.BillFile'),
        ),
    ]
