# Generated by Django 3.0.2 on 2020-02-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20200211_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='billfile',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
