# Generated by Django 3.0.2 on 2020-02-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_billfile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='billfile',
            name='md5_hash',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='billfile',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billfile',
            name='url',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
